export {default as Navbar} from "./Navbar/Navbar"
export {default as Sidebar} from "./Sidebar/Sidebar"
export {default as Header} from "./Header/Header"
export {default as SidebarSurah} from "./Sidebar/SidebarSurah/SidebarSurah"
export {default as Surah} from "./Surah/Surah"
export {default as Pagination} from "./Pagination/Pagination"
export {default as ScrollTop} from "./ScrollTop/ScrollTop"